module.exports = function(){
    return prequire([
        "./NewAppDialog" ,
        "./ToolBar" ,
        "./AppModel" ,
        "./ModelLoader" ,
        "./comm/Zoomer" ,
        "./comm/CardStack" ,
        "./comm/utils" ,
        "./graph/parts/Port" ,
        "./graph/parts/Part" ,
        "./graph/parts/HostPart" ,
        "./graph/parts/BePad" ,
        "./graph/parts/BeMotor" ,
        "./graph/parts/BeScreen" ,
        "./graph/GraphCanvas" ,
        "./graph/GraphTools" ,
        "./ui/WidgetHelper" ,
        "./ui/UITools" ,
        "./program/cards/CardBase" ,
        "./program/cards/basic" ,
        "./program/cards/ui" ,
        "./program/Program" ,
        "./program/ProgramTools" ,
        "./Workspace" ,
    ], require)
}