module.exports = {
    // "lv_arc_create": [null, [], "lv_obj_t *"],
    "lv_arc_set_start_angle": [null, [["uint16_t","start"]], "void"],
    "lv_arc_set_end_angle": [null, [["uint16_t","end"]], "void"],
    "lv_arc_set_angles": [null, [["uint16_t","start"],["uint16_t","end"]], "void"],
    "lv_arc_set_bg_start_angle": [null, [["uint16_t","start"]], "void"],
    "lv_arc_set_bg_end_angle": [null, [["uint16_t","end"]], "void"],
    "lv_arc_set_bg_angles": [null, [["uint16_t","start"],["uint16_t","end"]], "void"],
    "lv_arc_set_rotation": [null, [["uint16_t","rotation"]], "void"],
    "lv_arc_set_mode": [null, [["lv_arc_mode_t","type"]], "void"],
    "lv_arc_set_value": [null, [["int16_t","value"]], "void"],
    "lv_arc_set_range": [null, [["int16_t","min"],["int16_t","max"]], "void"],
    "lv_arc_set_change_rate": [null, [["uint16_t","rate"]], "void"],
    "lv_arc_get_angle_start": [null, [], "uint16_t"],
    "lv_arc_get_angle_end": [null, [], "uint16_t"],
    "lv_arc_get_bg_angle_start": [null, [], "uint16_t"],
    "lv_arc_get_bg_angle_end": [null, [], "uint16_t"],
    "lv_arc_get_value": [null, [], "int16_t"],
    "lv_arc_get_min_value": [null, [], "int16_t"],
    "lv_arc_get_max_value": [null, [], "int16_t"],
    "lv_arc_get_mode": [null, [], "lv_arc_mode_t"],
}
