module.exports = {
    // "lv_anim_init": [null, [], "void"],
    // "lv_anim_set_var": [null, [["void *","var"]], "void"],
    // "lv_anim_set_exec_cb": [null, [["lv_anim_exec_xcb_t","exec_cb"]], "void"],
    "lv_anim_set_time": [null, [["uint32_t","duration"]], "void"],
    "lv_anim_set_delay": [null, [["uint32_t","delay"]], "void"],
    "lv_anim_set_values": [null, [["int32_t","start"],["int32_t","end"]], "void"],
    "lv_anim_set_custom_exec_cb": [null, [["lv_anim_custom_exec_cb_t","exec_cb"]], "void"],
    "lv_anim_set_path_cb": [null, [["lv_anim_path_cb_t","path_cb"]], "void"],
    "lv_anim_set_start_cb": [null, [["lv_anim_start_cb_t","start_cb"]], "void"],
    "lv_anim_set_get_value_cb": [null, [["lv_anim_get_value_cb_t","get_value_cb"]], "void"],
    "lv_anim_set_ready_cb": [null, [["lv_anim_ready_cb_t","ready_cb"]], "void"],
    "lv_anim_set_playback_time": [null, [["uint32_t","time"]], "void"],
    "lv_anim_set_playback_delay": [null, [["uint32_t","delay"]], "void"],
    "lv_anim_set_repeat_count": [null, [["uint16_t","cnt"]], "void"],
    "lv_anim_set_repeat_delay": [null, [["uint32_t","delay"]], "void"],
    "lv_anim_set_early_apply": [null, [["bool","en"]], "void"],
    "lv_anim_set_user_data": [null, [["void *","user_data"]], "void"],
    "lv_anim_start": [null, [], "lv_anim_t *"],
    "lv_anim_get_delay": [null, [], "uint32_t"],
    "lv_anim_get_playtime": [null, [], "uint32_t"],
    "lv_anim_get_user_data": [null, [], "void *"],
    "lv_anim_del": [null, [["void *","var"],["lv_anim_exec_xcb_t","exec_cb"]], "bool"],
    "lv_anim_get": [null, [["void *","var"],["lv_anim_exec_xcb_t","exec_cb"]], "lv_anim_t *"],
    "lv_anim_custom_del": [null, [["lv_anim_custom_exec_cb_t","exec_cb"]], "bool"],
    "lv_anim_custom_get": [null, [["lv_anim_custom_exec_cb_t","exec_cb"]], "lv_anim_t *"],
    "lv_anim_speed_to_time": [null, [["uint32_t","speed"],["int32_t","start"],["int32_t","end"]], "uint32_t"],
    "lv_anim_path_linear": [null, [], "int32_t"],
    "lv_anim_path_ease_in": [null, [], "int32_t"],
    "lv_anim_path_ease_out": [null, [], "int32_t"],
    "lv_anim_path_ease_in_out": [null, [], "int32_t"],
    "lv_anim_path_overshoot": [null, [], "int32_t"],
    "lv_anim_path_bounce": [null, [], "int32_t"],
    "lv_anim_path_step": [null, [], "int32_t"],
    // "lv_anim_timeline_del": [null, [["lv_anim_timeline_t *","at"]], "void"],
    // "lv_anim_timeline_add": [null, [["lv_anim_timeline_t *","at"],["uint32_t","start_time"],["lv_anim_t *","a"]], "void"],
    // "lv_anim_timeline_start": [null, [["lv_anim_timeline_t *","at"]], "uint32_t"],
    // "lv_anim_timeline_stop": [null, [["lv_anim_timeline_t *","at"]], "void"],
    // "lv_anim_timeline_set_reverse": [null, [["lv_anim_timeline_t *","at"],["bool","reverse"]], "void"],
    // "lv_anim_timeline_set_progress": [null, [["lv_anim_timeline_t *","at"],["uint16_t","progress"]], "void"],
    // "lv_anim_timeline_get_playtime": [null, [["lv_anim_timeline_t *","at"]], "uint32_t"],
    // "lv_anim_timeline_get_reverse": [null, [["lv_anim_timeline_t *","at"]], "bool"],
}
