module.exports = {
    // "lv_canvas_create": [null, [], "lv_obj_t *"],
    // "lv_canvas_set_buffer": [null, [["void *","buf"],["lv_coord_t","w"],["lv_coord_t","h"],["lv_img_cf_t","cf"]], "void"],
    "lv_canvas_set_px_color": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_color_t","c"]], "void"],
    "lv_canvas_set_px": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_color_t","c"]], "void"],
    "lv_canvas_set_px_opa": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_opa_t","opa"]], "void"],
    "lv_canvas_set_palette": [null, [["uint8_t","id"],["lv_color_t","c"]], "void"],
    "lv_canvas_get_px": [null, [["lv_coord_t","x"],["lv_coord_t","y"]], "lv_color_t"],
    // "lv_canvas_get_img": [null, [], "lv_img_dsc_t *"],
    // "lv_canvas_copy_buf": [null, [["void *","to_copy"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","w"],["lv_coord_t","h"]], "void"],
    // "lv_canvas_transform": [null, [["lv_img_dsc_t *","img"],["int16_t","angle"],["uint16_t","zoom"],["lv_coord_t","offset_x"],["lv_coord_t","offset_y"],["int32_t","pivot_x"],["int32_t","pivot_y"],["bool","antialias"]], "void"],
    "lv_canvas_blur_hor": [null, [["lv_area_t *","area"],["uint16_t","r"]], "void"],
    "lv_canvas_blur_ver": [null, [["lv_area_t *","area"],["uint16_t","r"]], "void"],
    "lv_canvas_fill_bg": [null, [["lv_color_t","color"],["lv_opa_t","opa"]], "void"],
    "lv_canvas_draw_rect": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","w"],["lv_coord_t","h"],["lv_draw_rect_dsc_t *","draw_dsc"]], "void"],
    // "lv_canvas_draw_text": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","max_w"],["lv_draw_label_dsc_t *","draw_dsc"],["char *","txt"]], "void"],
    // "lv_canvas_draw_img": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["void *","src"],["lv_draw_img_dsc_t *","draw_dsc"]], "void"],
    // "lv_canvas_draw_line": [null, [["lv_point_t","points[]"],["uint32_t","point_cnt"],["lv_draw_line_dsc_t *","draw_dsc"]], "void"],
    // "lv_canvas_draw_polygon": [null, [["lv_point_t","points[]"],["uint32_t","point_cnt"],["lv_draw_rect_dsc_t *","draw_dsc"]], "void"],
    "lv_canvas_draw_arc": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","r"],["int32_t","start_angle"],["int32_t","end_angle"],["lv_draw_arc_dsc_t *","draw_dsc"]], "void"],
}
