module.exports = {
    "lv_disp_get_scr_act": [null, [["lv_disp_t *","disp"]], "lv_obj_t *"],
    "lv_disp_get_scr_prev": [null, [["lv_disp_t *","disp"]], "lv_obj_t *"],
    "lv_disp_load_scr": [null, [], "void"],
    "lv_disp_get_layer_top": [null, [["lv_disp_t *","disp"]], "lv_obj_t *"],
    "lv_disp_get_layer_sys": [null, [["lv_disp_t *","disp"]], "lv_obj_t *"],
    "lv_disp_set_theme": [null, [["lv_disp_t *","disp"],["lv_theme_t *","th"]], "void"],
    "lv_disp_get_theme": [null, [["lv_disp_t *","disp"]], "lv_theme_t *"],
    "lv_disp_set_bg_color": [null, [["lv_disp_t *","disp"],["lv_color_t","color"]], "void"],
    "lv_disp_set_bg_image": [null, [["lv_disp_t *","disp"],["void *","img_src"]], "void"],
    "lv_disp_set_bg_opa": [null, [["lv_disp_t *","disp"],["lv_opa_t","opa"]], "void"],
    "lv_disp_get_inactive_time": [null, [["lv_disp_t *","disp"]], "uint32_t"],
    "lv_disp_trig_activity": [null, [["lv_disp_t *","disp"]], "void"],
    "lv_disp_clean_dcache": [null, [["lv_disp_t *","disp"]], "void"],
    "lv_disp_dpx": [null, [["lv_disp_t *","disp"],["lv_coord_t","n"]], "lv_coord_t"],
    "lv_disp_drv_init": [null, [["lv_disp_drv_t *","driver"]], "void"],
    "lv_disp_draw_buf_init": [null, [["lv_disp_draw_buf_t *","draw_buf"],["void *","buf1"],["void *","buf2"],["uint32_t","size_in_px_cnt"]], "void"],
    "lv_disp_drv_register": [null, [["lv_disp_drv_t *","driver"]], "lv_disp_t *"],
    "lv_disp_drv_update": [null, [["lv_disp_t *","disp"],["lv_disp_drv_t *","new_drv"]], "void"],
    "lv_disp_remove": [null, [["lv_disp_t *","disp"]], "void"],
    "lv_disp_set_default": [null, [["lv_disp_t *","disp"]], "void"],
    "lv_disp_get_hor_res": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_ver_res": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_physical_hor_res": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_physical_ver_res": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_offset_x": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_offset_y": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_get_antialiasing": [null, [["lv_disp_t *","disp"]], "bool"],
    "lv_disp_get_dpi": [null, [["lv_disp_t *","disp"]], "lv_coord_t"],
    "lv_disp_set_rotation": [null, [["lv_disp_t *","disp"],["lv_disp_rot_t","rotation"]], "void"],
    "lv_disp_get_rotation": [null, [["lv_disp_t *","disp"]], "lv_disp_rot_t"],
    "lv_disp_flush_ready": [null, [["lv_disp_drv_t *","disp_drv"]], "void"],
    "lv_disp_flush_is_last": [null, [["lv_disp_drv_t *","disp_drv"]], "bool"],
    "lv_disp_get_next": [null, [["lv_disp_t *","disp"]], "lv_disp_t *"],
    "lv_disp_get_draw_buf": [null, [["lv_disp_t *","disp"]], "lv_disp_draw_buf_t *"],
    "lv_disp_drv_use_generic_set_px_cb": [null, [["lv_disp_drv_t *","disp_drv"],["lv_img_cf_t","cf"]], "void"],
}
