module.exports = {
    // "lv_label_create": [null, [], "lv_obj_t *"],
    "lv_label_set_text": [null, [["char *","text"]], "void"],
    // "lv_label_set_text_fmt": [null, [["char *","fmt"],["","..."]], "void"],
    "lv_label_set_text_static": [null, [["char *","text"]], "void"],
    "lv_label_set_long_mode": [null, [["lv_label_long_mode_t","long_mode"]], "void"],
    "lv_label_set_recolor": [null, [["bool","en"]], "void"],
    "lv_label_set_text_sel_start": [null, [["uint32_t","index"]], "void"],
    "lv_label_set_text_sel_end": [null, [["uint32_t","index"]], "void"],
    "lv_label_get_text": [null, [], "char *"],
    "lv_label_get_long_mode": [null, [], "lv_label_long_mode_t"],
    "lv_label_get_recolor": [null, [], "bool"],
    "lv_label_get_letter_pos": [null, [["uint32_t","char_id"],["lv_point_t *","pos"]], "void"],
    "lv_label_get_letter_on": [null, [["lv_point_t *","pos_in"]], "uint32_t"],
    "lv_label_is_char_under_pos": [null, [["lv_point_t *","pos"]], "bool"],
    "lv_label_get_text_selection_start": [null, [], "uint32_t"],
    "lv_label_get_text_selection_end": [null, [], "uint32_t"],
    "lv_label_ins_text": [null, [["uint32_t","pos"],["char *","txt"]], "void"],
    "lv_label_cut_text": [null, [["uint32_t","pos"],["uint32_t","cnt"]], "void"],
}
