module.exports = {
    // "lv_textarea_create": [null, [], "lv_obj_t *"],
    // "lv_textarea_add_char": [null, [["uint32_t","c"]], "void"],
    "lv_textarea_add_text": [null, [["char *","txt"]], "void"],
    "lv_textarea_del_char": [null, [], "void"],
    "lv_textarea_del_char_forward": [null, [], "void"],
    "lv_textarea_set_text": [null, [["char *","txt"]], "void"],
    "lv_textarea_set_placeholder_text": [null, [["char *","txt"]], "void"],
    "lv_textarea_set_cursor_pos": [null, [["int32_t","pos"]], "void"],
    "lv_textarea_set_cursor_click_pos": [null, [["bool","en"]], "void"],
    "lv_textarea_set_password_mode": [null, [["bool","en"]], "void"],
    "lv_textarea_set_one_line": [null, [["bool","en"]], "void"],
    "lv_textarea_set_accepted_chars": [null, [["char *","list"]], "void"],
    "lv_textarea_set_max_length": [null, [["uint32_t","num"]], "void"],
    "lv_textarea_set_insert_replace": [null, [["char *","txt"]], "void"],
    "lv_textarea_set_text_selection": [null, [["bool","en"]], "void"],
    "lv_textarea_set_password_show_time": [null, [["uint16_t","time"]], "void"],
    "lv_textarea_set_align": [null, [["lv_text_align_t","align"]], "void"],
    "lv_textarea_get_text": [null, [], "char *"],
    "lv_textarea_get_placeholder_text": [null, [], "char *"],
    "lv_textarea_get_label": [null, [], "lv_obj_t *"],
    "lv_textarea_get_cursor_pos": [null, [], "uint32_t"],
    "lv_textarea_get_cursor_click_pos": [null, [], "bool"],
    "lv_textarea_get_password_mode": [null, [], "bool"],
    "lv_textarea_get_one_line": [null, [], "bool"],
    "lv_textarea_get_accepted_chars": [null, [], "char *"],
    "lv_textarea_get_max_length": [null, [], "uint32_t"],
    "lv_textarea_text_is_selected": [null, [], "bool"],
    "lv_textarea_get_text_selection": [null, [], "bool"],
    "lv_textarea_get_password_show_time": [null, [], "uint16_t"],
    "lv_textarea_clear_selection": [null, [], "void"],
    "lv_textarea_cursor_right": [null, [], "void"],
    "lv_textarea_cursor_left": [null, [], "void"],
    "lv_textarea_cursor_down": [null, [], "void"],
    "lv_textarea_cursor_up": [null, [], "void"],
}
