module.exports = [
    "LV_FLEX_ALIGN_START",
    "LV_FLEX_ALIGN_END",
    "LV_FLEX_ALIGN_CENTER",
    "LV_FLEX_ALIGN_SPACE_EVENLY",
    "LV_FLEX_ALIGN_SPACE_AROUND",
    "LV_FLEX_ALIGN_SPACE_BETWEEN"
]