module.exports = {
    // "lv_img_src_get_type": [null, [["void *","src"]], "lv_img_src_t"],
    // "lv_img_cf_get_px_size": [null, [["lv_img_cf_t","cf"]], "uint8_t"],
    // "lv_img_cf_is_chroma_keyed": [null, [["lv_img_cf_t","cf"]], "bool"],
    // "lv_img_cf_has_alpha": [null, [["lv_img_cf_t","cf"]], "bool"],
    // "lv_img_buf_alloc": [null, [["lv_coord_t","w"],["lv_coord_t","h"],["lv_img_cf_t","cf"]], "lv_img_dsc_t *"],
    // "lv_img_buf_get_px_color": [null, [["lv_img_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_color_t","color"]], "lv_color_t"],
    // "lv_img_buf_get_px_alpha": [null, [["lv_img_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"]], "lv_opa_t"],
    // "lv_img_buf_set_px_color": [null, [["lv_img_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_color_t","c"]], "void"],
    // "lv_img_buf_set_px_alpha": [null, [["lv_img_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_opa_t","opa"]], "void"],
    // "lv_img_buf_set_palette": [null, [["lv_img_dsc_t *","dsc"],["uint8_t","id"],["lv_color_t","c"]], "void"],
    // "lv_img_buf_free": [null, [["lv_img_dsc_t *","dsc"]], "void"],
    // "lv_img_buf_get_img_size": [null, [["lv_coord_t","w"],["lv_coord_t","h"],["lv_img_cf_t","cf"]], "uint32_t"],
    // "lv_img_cache_set_size": [null, [["uint16_t","new_slot_num"]], "void"],
    // "lv_img_cache_invalidate_src": [null, [["void *","src"]], "void"],
    // "lv_img_decoder_get_info": [null, [["void *","src"],["lv_img_header_t *","header"]], "lv_res_t"],
    // "lv_img_decoder_open": [null, [["lv_img_decoder_dsc_t *","dsc"],["void *","src"],["lv_color_t","color"],["int32_t","frame_id"]], "lv_res_t"],
    // "lv_img_decoder_read_line": [null, [["lv_img_decoder_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","len"],["uint8_t *","buf"]], "lv_res_t"],
    // "lv_img_decoder_close": [null, [["lv_img_decoder_dsc_t *","dsc"]], "void"],
    // "lv_img_decoder_delete": [null, [["lv_img_decoder_t *","decoder"]], "void"],
    // "lv_img_decoder_set_info_cb": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_info_f_t","info_cb"]], "void"],
    // "lv_img_decoder_set_open_cb": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_open_f_t","open_cb"]], "void"],
    // "lv_img_decoder_set_read_line_cb": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_read_line_f_t","read_line_cb"]], "void"],
    // "lv_img_decoder_set_close_cb": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_close_f_t","close_cb"]], "void"],
    // "lv_img_decoder_built_in_info": [null, [["lv_img_decoder_t *","decoder"],["void *","src"],["lv_img_header_t *","header"]], "lv_res_t"],
    // "lv_img_decoder_built_in_open": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_dsc_t *","dsc"]], "lv_res_t"],
    // "lv_img_decoder_built_in_read_line": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_dsc_t *","dsc"],["lv_coord_t","x"],["lv_coord_t","y"],["lv_coord_t","len"],["uint8_t *","buf"]], "lv_res_t"],
    // "lv_img_decoder_built_in_close": [null, [["lv_img_decoder_t *","decoder"],["lv_img_decoder_dsc_t *","dsc"]], "void"],
    // "lv_img_create": [null, [], "lv_obj_t *"],
    // "lv_img_set_src": [null, [["char *","path"]], "void"],
    "lv_img_set_offset_x": [null, [["lv_coord_t","x"]], "void"],
    "lv_img_set_offset_y": [null, [["lv_coord_t","y"]], "void"],
    "lv_img_set_angle": [null, [["int16_t","angle"]], "void"],
    "lv_img_set_pivot": [null, [["lv_coord_t","x"],["lv_coord_t","y"]], "void"],
    "lv_img_set_zoom": [null, [["uint16_t","zoom"]], "void"],
    "lv_img_set_antialias": [null, [["bool","antialias"]], "void"],
    "lv_img_set_size_mode": [null, [["lv_img_size_mode_t","mode"]], "void"],
    // "lv_img_get_src": [null, [], "void *"],
    "lv_img_get_offset_x": [null, [], "lv_coord_t"],
    "lv_img_get_offset_y": [null, [], "lv_coord_t"],
    "lv_img_get_angle": [null, [], "uint16_t"],
    "lv_img_get_pivot": [null, [["lv_point_t *","pivot"]], "void"],
    "lv_img_get_zoom": [null, [], "uint16_t"],
    "lv_img_get_antialias": [null, [], "bool"],
    "lv_img_get_size_mode": [null, [], "lv_img_size_mode_t"],
}
