module.exports = {
    // "lv_obj_event_base": [null, [["lv_obj_class_t *","class_p"],["lv_event_t *","e"]], "lv_res_t"],
    // "lv_obj_add_event_cb": [null, [["lv_event_cb_t","event_cb"],["lv_event_code_t","filter"],["void *","user_data"]], "_lv_event_dsc_t *"],
    // "lv_obj_remove_event_cb": [null, [["lv_event_cb_t","event_cb"]], "bool"],
    // "lv_obj_remove_event_cb_with_user_data": [null, [["lv_event_cb_t","event_cb"],["void *","event_user_data"]], "bool"],
    // "lv_obj_remove_event_dsc": [null, [["lv_event_dsc_t *","event_dsc"]], "bool"],
    // "lv_obj_create": [null, [], "lv_obj_t *"],
    "lv_obj_add_flag": [null, [["lv_obj_flag_t","f"]], "void"],
    "lv_obj_clear_flag": [null, [["lv_obj_flag_t","f"]], "void"],
    "lv_obj_add_state": [null, [["lv_state_t","state"]], "void"],
    "lv_obj_clear_state": [null, [["lv_state_t","state"]], "void"],
    // "lv_obj_set_user_data": [null, [["void *","user_data"]], "void"],
    "lv_obj_has_flag": [null, [["lv_obj_flag_t","f"]], "bool"],
    "lv_obj_has_flag_any": [null, [["lv_obj_flag_t","f"]], "bool"],
    "lv_obj_get_state": [null, [], "lv_state_t"],
    "lv_obj_has_state": [null, [["lv_state_t","state"]], "bool"],
    // "lv_obj_get_group": [null, [], "void *"],
    // "lv_obj_is_group_def": [null, [], "bool"],
    // "lv_obj_get_user_data": [null, [], "void *"],
    // "lv_obj_check_type": [null, [["lv_obj_class_t *","class_p"]], "bool"],
    // "lv_obj_has_class": [null, [["lv_obj_class_t *","class_p"]], "bool"],
    // "lv_obj_get_class": [null, [], "lv_obj_class_t *"],
    // "lv_obj_class_create_obj": [null, [["lv_obj_class_t *","class_p"]], "_lv_obj_t *"],
    // "lv_obj_class_init_obj": [null, [], "void"],
    "lv_obj_allocate_spec_attr": [null, [], "void"],
    "lv_obj_is_valid": [null, [], "bool"],
    "lv_obj_dpx": [null, [["lv_coord_t","n"]], "lv_coord_t"],
    "lv_obj_is_editable": [null, [], "bool"],
    // "lv_obj_init_draw_rect_dsc": [null, [["uint32_t","part"],["lv_draw_rect_dsc_t *","draw_dsc"]], "void"],
    // "lv_obj_init_draw_label_dsc": [null, [["uint32_t","part"],["lv_draw_label_dsc_t *","draw_dsc"]], "void"],
    // "lv_obj_init_draw_img_dsc": [null, [["uint32_t","part"],["lv_draw_img_dsc_t *","draw_dsc"]], "void"],
    // "lv_obj_init_draw_line_dsc": [null, [["uint32_t","part"],["lv_draw_line_dsc_t *","draw_dsc"]], "void"],
    // "lv_obj_init_draw_arc_dsc": [null, [["uint32_t","part"],["lv_draw_arc_dsc_t *","draw_dsc"]], "void"],
    // "lv_obj_calculate_ext_draw_size": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_draw_dsc_init": [null, [["lv_obj_draw_part_dsc_t *","dsc"],["lv_area_t *","clip_area"]], "void"],
    // "lv_obj_draw_part_check_type": [null, [["lv_obj_draw_part_dsc_t *","dsc"],["lv_obj_class_t *","class_p"],["uint32_t","type"]], "bool"],
    // "lv_obj_refresh_ext_draw_size": [null, [], "void"],
    "lv_obj_set_pos": [null, [["lv_coord_t","x"],["lv_coord_t","y"]], "void"],
    "lv_obj_set_x": [null, [["lv_coord_t","x"]], "void"],
    "lv_obj_set_y": [null, [["lv_coord_t","y"]], "void"],
    "lv_obj_set_size": [null, [["lv_coord_t","w"],["lv_coord_t","h"]], "void"],
    "lv_obj_refr_size": [null, [], "bool"],
    "lv_obj_set_width": [null, [["lv_coord_t","w"]], "void"],
    "lv_obj_set_height": [null, [["lv_coord_t","h"]], "void"],
    "lv_obj_set_content_width": [null, [["lv_coord_t","w"]], "void"],
    "lv_obj_set_content_height": [null, [["lv_coord_t","h"]], "void"],
    "lv_obj_set_layout": [null, [["uint32_t","layout"]], "void"],
    "lv_obj_is_layout_positioned": [null, [], "bool"],
    "lv_obj_mark_layout_as_dirty": [null, [], "void"],
    "lv_obj_update_layout": [null, [], "void"],
    "lv_obj_set_align": [null, [["lv_align_t","align"]], "void"],
    "lv_obj_align": [null, [["lv_align_t","align"],["lv_coord_t","x_ofs"],["lv_coord_t","y_ofs"]], "void"],
    "lv_obj_align_to": [null, [["lv_obj_t *","base"],["lv_align_t","align"],["lv_coord_t","x_ofs"],["lv_coord_t","y_ofs"]], "void"],
    "lv_obj_center": [null, [], "void"],
    // "lv_obj_get_coords": [null, [["lv_area_t *","coords"]], "void"],
    "lv_obj_get_x": [null, [], "lv_coord_t"],
    "lv_obj_get_y": [null, [], "lv_coord_t"],
    "lv_obj_get_x_aligned": [null, [], "lv_coord_t"],
    "lv_obj_get_y_aligned": [null, [], "lv_coord_t"],
    "lv_obj_get_width": [null, [], "lv_coord_t"],
    "lv_obj_get_height": [null, [], "lv_coord_t"],
    "lv_obj_get_content_width": [null, [], "lv_coord_t"],
    "lv_obj_get_content_height": [null, [], "lv_coord_t"],
    "lv_obj_get_content_coords": [null, [["lv_area_t *","area"]], "void"],
    "lv_obj_get_self_width": [null, [], "lv_coord_t"],
    "lv_obj_get_self_height": [null, [], "lv_coord_t"],
    "lv_obj_refresh_self_size": [null, [], "bool"],
    "lv_obj_refr_pos": [null, [], "void"],
    "lv_obj_move_to": [null, [["lv_coord_t","x"],["lv_coord_t","y"]], "void"],
    "lv_obj_move_children_by": [null, [["lv_coord_t","x_diff"],["lv_coord_t","y_diff"],["bool","ignore_floating"]], "void"],
    "lv_obj_invalidate_area": [null, [["lv_area_t *","area"]], "void"],
    "lv_obj_invalidate": [null, [], "void"],
    "lv_obj_area_is_visible": [null, [["lv_area_t *","area"]], "bool"],
    "lv_obj_is_visible": [null, [], "bool"],
    "lv_obj_set_ext_click_area": [null, [["lv_coord_t","size"]], "void"],
    "lv_obj_get_click_area": [null, [["lv_area_t *","area"]], "void"],
    "lv_obj_hit_test": [null, [["lv_point_t *","point"]], "bool"],
    "lv_obj_set_scrollbar_mode": [null, [["lv_scrollbar_mode_t","mode"]], "void"],
    "lv_obj_set_scroll_dir": [null, [["lv_dir_t","dir"]], "void"],
    "lv_obj_set_scroll_snap_x": [null, [["lv_scroll_snap_t","align"]], "void"],
    "lv_obj_set_scroll_snap_y": [null, [["lv_scroll_snap_t","align"]], "void"],
    "lv_obj_get_scrollbar_mode": [null, [], "lv_scrollbar_mode_t"],
    "lv_obj_get_scroll_dir": [null, [], "lv_dir_t"],
    "lv_obj_get_scroll_snap_x": [null, [], "lv_scroll_snap_t"],
    "lv_obj_get_scroll_snap_y": [null, [], "lv_scroll_snap_t"],
    "lv_obj_get_scroll_x": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_y": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_top": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_bottom": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_left": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_right": [null, [], "lv_coord_t"],
    "lv_obj_get_scroll_end": [null, [["lv_point_t *","end"]], "void"],
    "lv_obj_scroll_by": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_scroll_to": [null, [["lv_coord_t","x"],["lv_coord_t","y"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_scroll_to_x": [null, [["lv_coord_t","x"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_scroll_to_y": [null, [["lv_coord_t","y"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_scroll_to_view": [null, [["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_scroll_to_view_recursive": [null, [["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_is_scrolling": [null, [], "bool"],
    "lv_obj_update_snap": [null, [["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_get_scrollbar_area": [null, [["lv_area_t *","hor"],["lv_area_t *","ver"]], "void"],
    "lv_obj_scrollbar_invalidate": [null, [], "void"],
    "lv_obj_readjust_scroll": [null, [["lv_anim_enable_t","anim_en"]], "void"],
    // "lv_obj_add_style": [null, [["lv_style_t *","style"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_remove_style": [null, [["lv_style_t *","style"],["lv_style_selector_t","selector"]], "void"],
    "lv_obj_remove_style_all": [null, [], "void"],
    // "lv_obj_report_style_change": [null, [["lv_style_t *","style"]], "void"],
    // "lv_obj_refresh_style": [null, [["lv_part_t","part"],["lv_style_prop_t","prop"]], "void"],
    // "lv_obj_enable_style_refresh": [null, [["bool","en"]], "void"],
    // "lv_obj_get_style_prop": [null, [["lv_part_t","part"],["lv_style_prop_t","prop"]], "lv_style_value_t"],
    // "lv_obj_set_local_style_prop": [null, [["lv_style_prop_t","prop"],["lv_style_value_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_get_local_style_prop": [null, [["lv_style_prop_t","prop"],["lv_style_value_t *","value"],["lv_style_selector_t","selector"]], "lv_res_t"],
    // "lv_obj_remove_local_style_prop": [null, [["lv_style_prop_t","prop"],["lv_style_selector_t","selector"]], "bool"],
    "lv_obj_fade_in": [null, [["uint32_t","time"],["uint32_t","delay"]], "void"],
    "lv_obj_fade_out": [null, [["uint32_t","time"],["uint32_t","delay"]], "void"],
    // "lv_obj_style_get_selector_state": [null, [["lv_style_selector_t","selector"]], "lv_state_t"],
    // "lv_obj_style_get_selector_part": [null, [["lv_style_selector_t","selector"]], "lv_part_t"],
    // "lv_obj_set_style_pad_all": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_hor": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_ver": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_gap": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_size": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_calculate_style_text_align": [null, [["lv_part_t","part"],["char *","txt"]], "lv_text_align_t"],
    // "lv_obj_get_style_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_min_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_max_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_height": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_min_height": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_max_height": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_x": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_y": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_align": [null, [["uint32_t","part"]], "lv_align_t"],
    // "lv_obj_get_style_transform_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_transform_height": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_translate_x": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_translate_y": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_transform_zoom": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_transform_angle": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_top": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_bottom": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_left": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_right": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_row": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_pad_column": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_radius": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_clip_corner": [null, [["uint32_t","part"]], "bool"],
    // "lv_obj_get_style_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_color_filter_dsc": [null, [["uint32_t","part"]], "lv_color_filter_dsc_t *"],
    // "lv_obj_get_style_color_filter_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_anim_time": [null, [["uint32_t","part"]], "uint32_t"],
    // "lv_obj_get_style_anim_speed": [null, [["uint32_t","part"]], "uint32_t"],
    // "lv_obj_get_style_transition": [null, [["uint32_t","part"]], "lv_style_transition_dsc_t *"],
    // "lv_obj_get_style_blend_mode": [null, [["uint32_t","part"]], "lv_blend_mode_t"],
    // "lv_obj_get_style_layout": [null, [["uint32_t","part"]], "uint16_t"],
    // "lv_obj_get_style_base_dir": [null, [["uint32_t","part"]], "lv_base_dir_t"],
    // "lv_obj_get_style_bg_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_bg_grad_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_grad_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_grad_dir": [null, [["uint32_t","part"]], "lv_grad_dir_t"],
    // "lv_obj_get_style_bg_main_stop": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_bg_grad_stop": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_bg_img_src": [null, [["uint32_t","part"]], "void *"],
    // "lv_obj_get_style_bg_img_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_bg_img_recolor": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_img_recolor_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_bg_img_recolor_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_bg_img_tiled": [null, [["uint32_t","part"]], "bool"],
    // "lv_obj_get_style_border_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_border_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_border_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_border_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_border_side": [null, [["uint32_t","part"]], "lv_border_side_t"],
    // "lv_obj_get_style_border_post": [null, [["uint32_t","part"]], "bool"],
    // "lv_obj_get_style_text_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_text_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_text_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_text_font": [null, [["uint32_t","part"]], "lv_font_t *"],
    // "lv_obj_get_style_text_letter_space": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_text_line_space": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_text_decor": [null, [["uint32_t","part"]], "lv_text_decor_t"],
    // "lv_obj_get_style_text_align": [null, [["uint32_t","part"]], "lv_text_align_t"],
    // "lv_obj_get_style_img_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_img_recolor": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_img_recolor_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_img_recolor_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_outline_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_outline_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_outline_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_outline_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_outline_pad": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_shadow_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_shadow_ofs_x": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_shadow_ofs_y": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_shadow_spread": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_shadow_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_shadow_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_shadow_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_line_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_line_dash_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_line_dash_gap": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_line_rounded": [null, [["uint32_t","part"]], "bool"],
    // "lv_obj_get_style_line_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_line_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_line_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_arc_width": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_arc_rounded": [null, [["uint32_t","part"]], "bool"],
    // "lv_obj_get_style_arc_color": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_arc_color_filtered": [null, [["uint32_t","part"]], "lv_color_t"],
    // "lv_obj_get_style_arc_opa": [null, [["uint32_t","part"]], "lv_opa_t"],
    // "lv_obj_get_style_arc_img_src": [null, [["uint32_t","part"]], "void *"],
    // "lv_obj_set_style_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_min_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_max_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_height": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_min_height": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_max_height": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_x": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_y": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_align": [null, [["lv_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_transform_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_transform_height": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_translate_x": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_translate_y": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_transform_zoom": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_transform_angle": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_top": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_bottom": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_left": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_right": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_row": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_pad_column": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_radius": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_clip_corner": [null, [["bool","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_color_filter_dsc": [null, [["lv_color_filter_dsc_t *","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_color_filter_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_anim_time": [null, [["uint32_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_anim_speed": [null, [["uint32_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_transition": [null, [["lv_style_transition_dsc_t *","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_blend_mode": [null, [["lv_blend_mode_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_layout": [null, [["uint16_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_base_dir": [null, [["lv_base_dir_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_grad_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_grad_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_grad_dir": [null, [["lv_grad_dir_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_main_stop": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_grad_stop": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_src": [null, [["void *","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_recolor": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_recolor_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_recolor_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_bg_img_tiled": [null, [["bool","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_side": [null, [["lv_border_side_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_border_post": [null, [["bool","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_font": [null, [["lv_font_t *","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_letter_space": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_line_space": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_decor": [null, [["lv_text_decor_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_text_align": [null, [["lv_text_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_img_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_img_recolor": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_img_recolor_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_img_recolor_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_outline_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_outline_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_outline_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_outline_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_outline_pad": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_ofs_x": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_ofs_y": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_spread": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_shadow_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_dash_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_dash_gap": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_rounded": [null, [["bool","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_line_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_width": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_rounded": [null, [["bool","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_color": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_color_filtered": [null, [["lv_color_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_opa": [null, [["lv_opa_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_arc_img_src": [null, [["void *","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_del": [null, [], "void"],
    // "lv_obj_clean": [null, [], "void"],
    // "lv_obj_del_delayed": [null, [["uint32_t","delay_ms"]], "void"],
    // "lv_obj_del_anim_ready_cb": [null, [["lv_anim_t *","a"]], "void"],
    // "lv_obj_del_async": [null, [], "void"],
    "lv_obj_set_parent": [null, [["lv_obj_t *"]], "void"],
    // "lv_obj_swap": [null, [], "void"],
    "lv_obj_move_to_index": [null, [["int32_t","index"]], "void"],
    "lv_obj_get_screen": [null, [], "_lv_obj_t *"],
    // "lv_obj_get_disp": [null, [], "lv_disp_t *"],
    "lv_obj_get_parent": [null, [], "_lv_obj_t *"],
    "lv_obj_get_child": [null, [["int32_t","id"]], "_lv_obj_t *"],
    "lv_obj_get_child_cnt": [null, [], "uint32_t"],
    "lv_obj_get_index": [null, [], "uint32_t"],
    // "lv_obj_tree_walk": [null, [["lv_obj_tree_walk_cb_t","cb"],["void *","user_data"]], "void"],
    "lv_obj_set_flex_flow": [null, [["lv_flex_flow_t","flow"]], "void"],
    "lv_obj_set_flex_align": [null, [["lv_flex_align_t","main_place"],["lv_flex_align_t","cross_place"],["lv_flex_align_t","track_cross_place"]], "void"],
    "lv_obj_set_flex_grow": [null, [["uint8_t","grow"]], "void"],
    // "lv_obj_set_style_flex_flow": [null, [["lv_flex_flow_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_flex_main_place": [null, [["lv_flex_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_flex_cross_place": [null, [["lv_flex_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_flex_track_place": [null, [["lv_flex_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_flex_grow": [null, [["uint8_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_get_style_flex_flow": [null, [["uint32_t","part"]], "lv_flex_flow_t"],
    // "lv_obj_get_style_flex_main_place": [null, [["uint32_t","part"]], "lv_flex_align_t"],
    // "lv_obj_get_style_flex_cross_place": [null, [["uint32_t","part"]], "lv_flex_align_t"],
    // "lv_obj_get_style_flex_track_place": [null, [["uint32_t","part"]], "lv_flex_align_t"],
    // "lv_obj_get_style_flex_grow": [null, [["uint32_t","part"]], "uint8_t"],
    // "lv_obj_set_grid_dsc_array": [null, [["lv_coord_t","col_dsc[]"],["lv_coord_t","row_dsc[]"]], "void"],
    // "lv_obj_set_grid_align": [null, [["lv_grid_align_t","column_align"],["lv_grid_align_t","row_align"]], "void"],
    // "lv_obj_set_grid_cell": [null, [["lv_grid_align_t","column_align"],["uint8_t","col_pos"],["uint8_t","col_span"],["lv_grid_align_t","row_align"],["uint8_t","row_pos"],["uint8_t","row_span"]], "void"],
    // "lv_obj_set_style_grid_row_dsc_array": [null, [["lv_coord_t","value[]"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_column_dsc_array": [null, [["lv_coord_t","value[]"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_row_align": [null, [["lv_grid_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_column_align": [null, [["lv_grid_align_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_column_pos": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_column_span": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_row_pos": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_row_span": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_x_align": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_set_style_grid_cell_y_align": [null, [["lv_coord_t","value"],["lv_style_selector_t","selector"]], "void"],
    // "lv_obj_get_style_grid_row_dsc_array": [null, [["uint32_t","part"]], "lv_coord_t *"],
    // "lv_obj_get_style_grid_column_dsc_array": [null, [["uint32_t","part"]], "lv_coord_t *"],
    // "lv_obj_get_style_grid_row_align": [null, [["uint32_t","part"]], "lv_grid_align_t"],
    // "lv_obj_get_style_grid_column_align": [null, [["uint32_t","part"]], "lv_grid_align_t"],
    // "lv_obj_get_style_grid_cell_column_pos": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_grid_cell_column_span": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_grid_cell_row_pos": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_grid_cell_row_span": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_grid_cell_x_align": [null, [["uint32_t","part"]], "lv_coord_t"],
    // "lv_obj_get_style_grid_cell_y_align": [null, [["uint32_t","part"]], "lv_coord_t"],
    "lv_obj_set_tile": [null, [["lv_obj_t *","tile_obj"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_set_tile_id": [null, [["uint32_t","col_id"],["uint32_t","row_id"],["lv_anim_enable_t","anim_en"]], "void"],
    "lv_obj_move_foreground": [null, [], "void"],
    "lv_obj_move_background": [null, [], "void"],
    "lv_obj_get_child_id": [null, [], "uint32_t"],
}